### ISSUE TITLE
Cannot find module 'babel-plugin-transform-inline-environment-variables'

### ISSUE THREAD

**Issue by nelsonthedev** [luizmuraro/StoreApp#1]
Hello there!

First of all, congrats for the initiative of creating this app! It looks really amazing and will definitely help others to learn React Native!

Secondly, I went through the installation steps and then I ran `yarn android`. When the app was launched in the android emulator, I got the following error:

![image](https://user-images.githubusercontent.com/17322056/170388924-36080729-8c3d-44f7-8bd4-10689c74498f.png)

Could you please assist on solving this? Thanks a lot!

**Comment by nelsonthedev** [comment]
Ok, I was able to fix it by adding the plugin to the devDependencies. After that, I've got another similar issue asking for react-native-reanimated. I've fixed it by running the following commands:

`yarn add -D babel-plugin-transform-inline-environment-variables` 

`yarn add react-native-reanimated`

Maybe those can be added to package.json.

Thanks!

**Comment by luizmuraro** [comment]
Hey @leonardonelson91, I'm happy that you liked the project and I really hope that it will assist people to learn React-Native!

Thanks for the feedback, I appreciate for already giving the solution about the error, and I'll give a look at it to understand better why this happened, I won't commit to the solution yet, because the project was made for a job challenge, so I can't change it until the coding interview, after the interview I'll publish the solution!

Thanks again mate!

**Comment by luizmuraro** [comment]
@leonardonelson91 Fixes done! Thanks for the alert!
